### ISSUE TITLE
Application State

### ISSUE THREAD

**Issue by DeanSCND** [edudnyk/SheeKit#6]
I have been playing around with this a bit (nice work BTW) and noticed that the presented view does not seem to have access to ApplicationState object. Any clue why that is? I have worked around it by isolating binding in cases where this is used but thought you might like to know that. Is this an issue, by design or just a limitation of how the concept was implemented in UIKit?

Cheers

-dean

**Comment by DeanSCND** [comment]
Check out this public repo. I created a small app that reproduces this. Let me know if I'm missing something. Also. I'm going to try another test where I see if I can pass in the state rather than accessing it globally. I'll let you know if that works.

https://github.com/DeanSCND/SheeKitTest

The error I get is 

022-02-14 13:00:53.542819-0700 SheeKitTest[33604:22948158] SwiftUI/EnvironmentObject.swift:70: Fatal error: No ObservableObject of type ApplicationState found. A View.environmentObject(_:) for ApplicationState may be missing as an ancestor of this view.

Which is expected if the state object is not defined but in this case it is.

**Comment by edudnyk** [comment]
Hey @DeanSCND,

Thanks for clarification.

Since SheeKit works as a sandwich (read more [here](https://medium.com/nerd-for-tech/customise-and-resize-sheets-in-swiftui-df9fae7c369b)), it creates a gap in automatic environment propagation. 

In SwiftUI there is no public API to manually forward all parent environment into the child view.

To fix that, pass whichever environment you may need, into sheet content, i.e.

```swift
.shee(
    isPresented:$presetShee,
    presentationStyle: .formSheet(properties: .init(detents: [ .large(), .large() ], animatesSelectedDetentIdentifierChange: true)),
    presentedViewControllerParameters: presentedViewControllerParameters) {
        SubView()
            .environmentObject(applicationState)
    }
```

In case if you find a way to manually forward all parent environment into the child in addition to the [customized one](https://github.com/edudnyk/SheeKit/blob/4bdc3b7ff784b893ec8f802e4154cd0d0bdf1b46/Sources/SheeKit/SheetModifier.swift#L84), I'll accept your PR with pleasure.

**Comment by DeanSCND** [comment]
Great explanation, and it's what I figured. The functionality you've developed is more that great and worth working around this. I honestly rather components not have to be aware of more than themselves anyway but unfortunately the sprawl of the app I'm building kinda forced my hand. Don't PR it, it's worth dealing with and totally understand why. Thanks for indulging me.
